@echo off
echo Starting Backend...
start "Backend API" cmd /k "cd backend && call venv\Scripts\activate && uvicorn main:app --reload --host 0.0.0.0 --port 8000"

echo Starting Frontend...
start "Frontend Web" cmd /k "cd web && npm run dev"

echo Avishkar System Launching...
